source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'EPSignature_Example' do
  pod 'EPSignature', :path=> '../'
end

target 'EPSignature_Tests' do
  pod 'EPSignature', :path=> '../'

end
